name: Claude Reddit Curator poster

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  run-claude-sample:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.4'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install anthropic
    
    - name: Run Anthropic script
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: python ./python/demo.py


    - name: Debug - List directory contents
      run: |
        echo "Contents of website/dailyData:"
        ls -l website/dailyData || echo "Directory not found"



    - name: Check new output files
      run: |
        echo "Checking for new files in website/dailyData:"
        new_files=$(git ls-files --others --exclude-standard website/dailyData/)
        if [ -z "$new_files" ]; then
          echo "No new files found."
        else
          echo "New files found:"
          for file in $new_files; do
            echo "File: $file"
            echo "Contents:"
            cat "$file"
            echo "File size:"
            ls -l "$file"
            echo "----------------------"
          done
        fi

    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Check for changes
      id: git-check
      run: |
        git add website/dailyData/datesIndex.jsonl
        git status
        git diff --staged --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

    - name: Debug - Environment
      run: |
        echo "GitHub workspace: $GITHUB_WORKSPACE"
        echo "GitHub event name: $GITHUB_EVENT_NAME"
        echo "GitHub repository: $GITHUB_REPOSITORY"
        echo "GitHub ref: $GITHUB_REF"

    - name: Create Pull Request
      if: steps.git-check.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update data from Claude Reddit Curator
        title: 'Update: Claude Reddit Curator data'
        body: |
          This is an automated PR created by the Claude Reddit Curator poster workflow.
          It updates the data based on the latest run of the script.
        branch: update-claude-data
        base: main

    - name: Debug - PR Creation
      if: steps.git-check.outputs.changes == 'true'
      run: |
        echo "Pull request creation attempted"
        echo "Check the Actions tab for any error messages"