name: Claude Reddit Curator poster

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  run-claude-sample:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install @anthropic-ai/sdk
    - name: Run Anthropic script
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: node ../website/out/sample.js
