name: Claude Reddit Curator poster

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  run-claude-sample:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.4'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install anthropic
    
    - name: Run Anthropic script
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: python ./python/demo.py

    - name: Check output file
      run: |
        echo "Output file contents:"
        cat website/dailyData/datesIndex.jsonl
        echo "File size:"
        ls -l website/dailyData/datesIndex.jsonl

    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Check for changes
      id: git-check
      run: |
        git add website/dailyData/datesIndex.jsonl
        git status
        git diff --staged --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

    - name: Create Pull Request
      if: steps.git-check.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update data from Claude Reddit Curator
        title: 'Update: Claude Reddit Curator data'
        body: |
          This is an automated PR created by the Claude Reddit Curator poster workflow.
          It updates the data based on the latest run of the script.
        branch: update-claude-data
        base: main